name: Validate Python code with ruff

on:
  pull_request:

jobs:
  ruff:
    name: ruff
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Run Ruff linter
        uses: astral-sh/ruff-action@v3
        with:
          args: check
          src: lambda

      - name: Run Ruff formatter
        uses: astral-sh/ruff-action@v3
        with:
          args: format --check
          src: lambda
